---

alert_policies:
    - name: "EE Paas LIVE (CF servers)"
      tags:
      - live
      - live-diego
    - name: "EE Paas DEV (CF Servers)"
      tags:
      - dev
      - dev-diego
      - dev-postgresql

